[project]
name = "first-flask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.1.2",
    "hypercorn>=0.17.3",
    "python-dotenv>=1.1.1",
]
